Script started on Tue 18 Nov 2014 08:42:02 PM PST
~
hchu007@hammer $ ls
[0m[01;32ma.out[0m*         assn3.asm  assn5 (2).asm  [01;34mDesktop[0m/    [01;34mDownloads[0m/  ex2.asm  fork.cpp        [01;32mIntVector.cpp~[0m*  [01;34mlab4cs100[0m/  [01;31mlab7.tgz[0m  [01;32mmain.cpp[0m*  [01;34mPictures[0m/  [01;34mrshell[0m/    temp.cpp    Timer.h     [01;34mVideos[0m/
assn3 (1).asm  assn4.asm  assn5.asm      [01;34mDocuments[0m/  ex1.asm     ex3.asm  [01;32mIntVector.cpp[0m*  lab3ex1.asm      [01;31mlab5.tgz[0m    ls.cpp    [01;34mMusic[0m/     [01;34mPublic[0m/    [01;34mrshell-1[0m/  [01;34mTemplates[0m/  [01;34mucr-cs100[0m/
[m~
hchu007@hammer $ cd rshell
~/rshell
hchu007@hammer $ binrsh[K[K[K/rshell
hchu007@hammer.cs.ucr.edu$ #BEGIN HW2 PIPING TESTS            TESTS
hchu007@hammer.cs.ucr.edu$ #tests I/O rede irection
hchu007@hammer.cs.ucr.edu$ ls
bin  LICENSE  Makefile	piping.script  README.md  src  tests
hchu007@hammer.cs.ucr.edu$ cat License        ICENSE >               wc -l M   < Makefile
22
hchu007@hammer.cs.ucr.edu$ ls > output1
hchu007@hammer.cs.ucr.edu$ ls >> output2 1             cat output1
bin
LICENSE
Makefile
output1
piping.script
README.md
src
tests
hchu007@hammer.cs.ucr.edu$ ls >>    -l >> output1
hchu007@hammer.cs.ucr.edu$ cat output1
bin
LICENSE
Makefile
output1
piping.script
README.md
src
tests
total 24
drwx------ 2 hchu007 csmajs 4096 Nov 18 19:58 bin
-rw------- 1 hchu007 csmajs   90 Nov 18 19:57 LICENSE
-rw------- 1 hchu007 csmajs  556 Nov 18 19:57 Makefile
-rw------- 1 hchu007 csmajs   63 Nov 18 20:42 output1
-rw------- 1 hchu007 csmajs    0 Nov 18 20:40 piping.script
-rw------- 1 hchu007 csmajs 3076 Nov 18 19:57 README.md
drwx------ 2 hchu007 csmajs 4096 Nov 18 19:57 src
drwx------ 2 hchu007 csmajs 4096 Nov 18 19:57 tests
hchu007@hammer.cs.ucr.edu$ rm output1
hchu007@hammer.cs.ucr.edu$ ls
bin  LICENSE  Makefile	piping.script  README.md  src  tests
hchu007@hammer.cs.ucr.edu$ wc -l Makefile          < Makefile > output1
hchu007@hammer.cs.ucr.edu$ ls  cat output1
22
hchu007@hammer.cs.ucr.edu$ wc < m m Makefile >> output1
hchu007@hammer.cs.ucr.edu$ cat output1
22
 22  92 556
hchu007@hammer.cs.ucr.edu$ #TEST PI        ls -l >>>   >     > output1
hchu007@hammer.cs.ucr.edu$ cat output1
22
 22  92 556
total 24
drwx------ 2 hchu007 csmajs 4096 Nov 18 19:58 bin
-rw------- 1 hchu007 csmajs   90 Nov 18 19:57 LICENSE
-rw------- 1 hchu007 csmajs  556 Nov 18 19:57 Makefile
-rw------- 1 hchu007 csmajs   15 Nov 18 20:43 output1
-rw------- 1 hchu007 csmajs    0 Nov 18 20:40 piping.script
-rw------- 1 hchu007 csmajs 3076 Nov 18 19:57 README.md
drwx------ 2 hchu007 csmajs 4096 Nov 18 19:57 src
drwx------ 2 hchu007 csmajs 4096 Nov 18 19:57 tests
hchu007@hammer.cs.ucr.edu$ #TEST CONNECTORS
hchu007@hammer.cs.ucr.edu$ #SUCH    PIPES AS CONNECTOR           ND THEN PIPES WITH I/O
hchu007@hammer.cs.ucr.edu$ ls -l | Hea    head -5
total 28
drwx------ 2 hchu007 csmajs 4096 Nov 18 19:58 bin
-rw------- 1 hchu007 csmajs   90 Nov 18 19:57 LICENSE
-rw------- 1 hchu007 csmajs  556 Nov 18 19:57 Makefile
-rw------- 1 hchu007 csmajs  455 Nov 18 20:44 output1
hchu007@hammer.cs.ucr.edu$ ls -l | head -5\ |tail-1
execvp: No such file or directory
hchu007@hammer.cs.ucr.edu$ ls -l | head -5| tail     tail -1
-rw------- 1 hchu007 csmajs  455 Nov 18 20:44 output1
hchu007@hammer.cs.ucr.edu$ ||
execvp: No such file or directory
hchu007@hammer.cs.ucr.edu$ | |
execvp: No such file or directory
hchu007@hammer.cs.ucr.edu$ ls -l |
ls: cannot access |: No such file or directory
hchu007@hammer.cs.ucr.edu$ wc -l l | < t ls -l | head -5 | tail -2
open: No such file or directory
dup2: Bad file descriptor
ls

~/rshell
hchu007@hammer $ bin/l[Krshell
hchu007@hammer.cs.ucr.edu$ ls
bin  LICENSE  Makefile	output1  piping.script	README.md  src	tests
hchu007@hammer.cs.ucr.edu$ rm output1
hchu007@hammer.cs.ucr.edu$ ls
bin  LICENSE  Makefile	piping.script  README.md  src  tests
hchu007@hammer.cs.ucr.edu$ cat < LICEMS  NSE | tr A-Z a-  z | tee output1 | tr a-z A-Z > output2 * &
hchu007@hammer.cs.ucr.edu$ cat Li ICENSE
Copyright (c) 2014, Harry Chu
All rights reserved.
All content is licensed under the BSD3.hchu007@hammer.cs.ucr.edu$ cat output1
copyright (c) 2014, harry chu
all rights reserved.
all content is licensed under the bsd3.hchu007@hammer.cs.ucr.edu$ cat output2
COPYRIGHT (C) 2014, HARRY CHU
ALL RIGHTS RESERVED.
ALL CONTENT IS LICENSED UNDER THE BSD3.hchu007@hammer.cs.ucr.edu$ echo extra credit rocks s | cat
extra credit rocks
hchu007@hammer.cs.ucr.edu$ a a cat <<< "extra credit rocks"
open: No such file or directory
dup2: Bad file descriptor
open: No such file or directory
dup2: Bad file descriptor
open: No such file or directory
dup2: Bad file descriptor
g++     
~/rshell
hchu007@hammer $ valgrind --leak-check=yes bin/ls -alR[C[C[C[C[C[K[K[K[K[K[K[Krshell
==36887== Memcheck, a memory error detector
==36887== Copyright (C) 2002-2012, and GNU GPL'd, by Julian Seward et al.
==36887== Using Valgrind-3.8.1 and LibVEX; rerun with -h for copyright info
==36887== Command: bin/rshell
==36887== 
hchu007@hammer.cs.ucr.edu$ ls
==36888== Invalid write of size 1
==36888==    at 0x4A080CF: __GI_strcpy (mc_replace_strmem.c:443)
==36888==    by 0x401AF2: execute(std::vector<std::string, std::allocator<std::string> >) (in /home/csmajs/hchu007/rshell/bin/rshell)
==36888==    by 0x4020A0: pipes1(std::vector<std::string, std::allocator<std::string> >) (in /home/csmajs/hchu007/rshell/bin/rshell)
==36888==    by 0x40281F: main (in /home/csmajs/hchu007/rshell/bin/rshell)
==36888==  Address 0x4c331e2 is 0 bytes after a block of size 2 alloc'd
==36888==    at 0x4A07192: operator new[](unsigned long) (vg_replace_malloc.c:363)
==36888==    by 0x401AB2: execute(std::vector<std::string, std::allocator<std::string> >) (in /home/csmajs/hchu007/rshell/bin/rshell)
==36888==    by 0x4020A0: pipes1(std::vector<std::string, std::allocator<std::string> >) (in /home/csmajs/hchu007/rshell/bin/rshell)
==36888==    by 0x40281F: main (in /home/csmajs/hchu007/rshell/bin/rshell)
==36888== 
==36888== Invalid read of size 1
==36888==    at 0x4A07B84: __GI_strchr (mc_replace_strmem.c:223)
==36888==    by 0x30508AD423: execvpe (in /lib64/libc-2.12.so)
==36888==    by 0x401B24: execute(std::vector<std::string, std::allocator<std::string> >) (in /home/csmajs/hchu007/rshell/bin/rshell)
==36888==    by 0x4020A0: pipes1(std::vector<std::string, std::allocator<std::string> >) (in /home/csmajs/hchu007/rshell/bin/rshell)
==36888==    by 0x40281F: main (in /home/csmajs/hchu007/rshell/bin/rshell)
==36888==  Address 0x4c331e2 is 0 bytes after a block of size 2 alloc'd
==36888==    at 0x4A07192: operator new[](unsigned long) (vg_replace_malloc.c:363)
==36888==    by 0x401AB2: execute(std::vector<std::string, std::allocator<std::string> >) (in /home/csmajs/hchu007/rshell/bin/rshell)
==36888==    by 0x4020A0: pipes1(std::vector<std::string, std::allocator<std::string> >) (in /home/csmajs/hchu007/rshell/bin/rshell)
==36888==    by 0x40281F: main (in /home/csmajs/hchu007/rshell/bin/rshell)
==36888== 
==36888== Invalid read of size 1
==36888==    at 0x4A07FC4: __GI_strlen (mc_replace_strmem.c:404)
==36888==    by 0x30508AD56C: execvpe (in /lib64/libc-2.12.so)
==36888==    by 0x401B24: execute(std::vector<std::string, std::allocator<std::string> >) (in /home/csmajs/hchu007/rshell/bin/rshell)
==36888==    by 0x4020A0: pipes1(std::vector<std::string, std::allocator<std::string> >) (in /home/csmajs/hchu007/rshell/bin/rshell)
==36888==    by 0x40281F: main (in /home/csmajs/hchu007/rshell/bin/rshell)
==36888==  Address 0x4c331e2 is 0 bytes after a block of size 2 alloc'd
==36888==    at 0x4A07192: operator new[](unsigned long) (vg_replace_malloc.c:363)
==36888==    by 0x401AB2: execute(std::vector<std::string, std::allocator<std::string> >) (in /home/csmajs/hchu007/rshell/bin/rshell)
==36888==    by 0x4020A0: pipes1(std::vector<std::string, std::allocator<std::string> >) (in /home/csmajs/hchu007/rshell/bin/rshell)
==36888==    by 0x40281F: main (in /home/csmajs/hchu007/rshell/bin/rshell)
==36888== 
==36888== Invalid read of size 1
==36888==    at 0x4A08DEC: memcpy (mc_replace_strmem.c:882)
==36888==    by 0x30508AD5C6: execvpe (in /lib64/libc-2.12.so)
==36888==    by 0x401B24: execute(std::vector<std::string, std::allocator<std::string> >) (in /home/csmajs/hchu007/rshell/bin/rshell)
==36888==    by 0x4020A0: pipes1(std::vector<std::string, std::allocator<std::string> >) (in /home/csmajs/hchu007/rshell/bin/rshell)
==36888==    by 0x40281F: main (in /home/csmajs/hchu007/rshell/bin/rshell)
==36888==  Address 0x4c331e2 is 0 bytes after a block of size 2 alloc'd
==36888==    at 0x4A07192: operator new[](unsigned long) (vg_replace_malloc.c:363)
==36888==    by 0x401AB2: execute(std::vector<std::string, std::allocator<std::string> >) (in /home/csmajs/hchu007/rshell/bin/rshell)
==36888==    by 0x4020A0: pipes1(std::vector<std::string, std::allocator<std::string> >) (in /home/csmajs/hchu007/rshell/bin/rshell)
==36888==    by 0x40281F: main (in /home/csmajs/hchu007/rshell/bin/rshell)
==36888== 
==36888== Syscall param execve(argv[i]) points to unaddressable byte(s)
==36888==    at 0x30508ACDA7: execve (in /lib64/libc-2.12.so)
==36888==    by 0x30508AD630: execvpe (in /lib64/libc-2.12.so)
==36888==    by 0x401B24: execute(std::vector<std::string, std::allocator<std::string> >) (in /home/csmajs/hchu007/rshell/bin/rshell)
==36888==    by 0x4020A0: pipes1(std::vector<std::string, std::allocator<std::string> >) (in /home/csmajs/hchu007/rshell/bin/rshell)
==36888==    by 0x40281F: main (in /home/csmajs/hchu007/rshell/bin/rshell)
==36888==  Address 0x4c331e2 is 0 bytes after a block of size 2 alloc'd
==36888==    at 0x4A07192: operator new[](unsigned long) (vg_replace_malloc.c:363)
==36888==    by 0x401AB2: execute(std::vector<std::string, std::allocator<std::string> >) (in /home/csmajs/hchu007/rshell/bin/rshell)
==36888==    by 0x4020A0: pipes1(std::vector<std::string, std::allocator<std::string> >) (in /home/csmajs/hchu007/rshell/bin/rshell)
==36888==    by 0x40281F: main (in /home/csmajs/hchu007/rshell/bin/rshell)
==36888== 
bin  LICENSE  Makefile	output1  output2  piping.script  README.md  src  tests
hchu007@hammer.cs.ucr.edu$ rm    cat < e LICENSE | tr A-Z a-z | tee output1 | tr a-z A-Z > output2 &
==36925== Invalid write of size 1
==36925==    at 0x4A080CF: __GI_strcpy (mc_replace_strmem.c:443)
==36925==    by 0x401AF2: execute(std::vector<std::string, std::allocator<std::string> >) (in /home/csmajs/hchu007/rshell/bin/rshell)
==36925==    by 0x402160: pipes1(std::vector<std::string, std::allocator<std::string> >) (in /home/csmajs/hchu007/rshell/bin/rshell)
==36925==    by 0x40281F: main (in /home/csmajs/hchu007/rshell/bin/rshell)
==36925==  Address 0x4c39243 is 0 bytes after a block of size 3 alloc'd
==36925==    at 0x4A07192: operator new[](unsigned long) (vg_replace_malloc.c:363)
==36925==    by 0x401AB2: execute(std::vector<std::string, std::allocator<std::string> >) (in /home/csmajs/hchu007/rshell/bin/rshell)
==36925==    by 0x402160: pipes1(std::vector<std::string, std::allocator<std::string> >) (in /home/csmajs/hchu007/rshell/bin/rshell)
==36925==    by 0x40281F: main (in /home/csmajs/hchu007/rshell/bin/rshell)
==36925== 
==36925== Invalid read of size 1
==36925==    at 0x4A08538: __GI_strcmp (mc_replace_strmem.c:730)
==36925==    by 0x4017C1: checkIO(char**) (in /home/csmajs/hchu007/rshell/bin/rshell)
==36925==    by 0x401B0E: execute(std::vector<std::string, std::allocator<std::string> >) (in /home/csmajs/hchu007/rshell/bin/rshell)
==36925==    by 0x402160: pipes1(std::vector<std::string, std::allocator<std::string> >) (in /home/csmajs/hchu007/rshell/bin/rshell)
==36925==    by 0x40281F: main (in /home/csmajs/hchu007/rshell/bin/rshell)
==36925==  Address 0x4c39291 is 0 bytes after a block of size 1 alloc'd
==36925==    at 0x4A07192: operator new[](unsigned long) (vg_replace_malloc.c:363)
==36925==    by 0x401AB2: execute(std::vector<std::string, std::allocator<std::string> >) (in /home/csmajs/hchu007/rshell/bin/rshell)
==36925==    by 0x402160: pipes1(std::vector<std::string, std::allocator<std::string> >) (in /home/csmajs/hchu007/rshell/bin/rshell)
==36925==    by 0x40281F: main (in /home/csmajs/hchu007/rshell/bin/rshell)
==36925== 
==36925== Syscall param open(filename) points to unaddressable byte(s)
==36925==    at 0x30508DB3B0: __open_nocancel (in /lib64/libc-2.12.so)
==36925==    by 0x401811: checkIO(char**) (in /home/csmajs/hchu007/rshell/bin/rshell)
==36925==    by 0x401B0E: execute(std::vector<std::string, std::allocator<std::string> >) (in /home/csmajs/hchu007/rshell/bin/rshell)
==36925==    by 0x402160: pipes1(std::vector<std::string, std::allocator<std::string> >) (in /home/csmajs/hchu007/rshell/bin/rshell)
==36925==    by 0x40281F: main (in /home/csmajs/hchu007/rshell/bin/rshell)
==36925==  Address 0x4c392e7 is 0 bytes after a block of size 7 alloc'd
==36925==    at 0x4A07192: operator new[](unsigned long) (vg_replace_malloc.c:363)
==36925==    by 0x401AB2: execute(std::vector<std::string, std::allocator<std::string> >) (in /home/csmajs/hchu007/rshell/bin/rshell)
==36925==    by 0x402160: pipes1(std::vector<std::string, std::allocator<std::string> >) (in /home/csmajs/hchu007/rshell/bin/rshell)
==36925==    by 0x40281F: main (in /home/csmajs/hchu007/rshell/bin/rshell)
==36925== 
==36925== Invalid read of size 1
==36925==    at 0x4A07B84: __GI_strchr (mc_replace_strmem.c:223)
==36925==    by 0x30508AD423: execvpe (in /lib64/libc-2.12.so)
==36925==    by 0x401B24: execute(std::vector<std::string, std::allocator<std::string> >) (in /home/csmajs/hchu007/rshell/bin/rshell)
==36925==    by 0x402160: pipes1(std::vector<std::string, std::allocator<std::string> >) (in /home/csmajs/hchu007/rshell/bin/rshell)
==36925==    by 0x40281F: main (in /home/csmajs/hchu007/rshell/bin/rshell)
==36925==  Address 0x4c39243 is 0 bytes after a block of size 3 alloc'd
==36925==    at 0x4A07192: operator new[](unsigned long) (vg_replace_malloc.c:363)
==36925==    by 0x401AB2: execute(std::vector<std::string, std::allocator<std::string> >) (in /home/csmajs/hchu007/rshell/bin/rshell)
==36925==    by 0x402160: pipes1(std::vector<std::string, std::allocator<std::string> >) (in /home/csmajs/hchu007/rshell/bin/rshell)
==36925==    by 0x40281F: main (in /home/csmajs/hchu007/rshell/bin/rshell)
==36925== 
==36925== Invalid read of size 1
==36925==    at 0x4A07FC4: __GI_strlen (mc_replace_strmem.c:404)
==36925==    by 0x30508AD56C: execvpe (in /lib64/libc-2.12.so)
==36925==    by 0x401B24: execute(std::vector<std::string, std::allocator<std::string> >) (in /home/csmajs/hchu007/rshell/bin/rshell)
==36925==    by 0x402160: pipes1(std::vector<std::string, std::allocator<std::string> >) (in /home/csmajs/hchu007/rshell/bin/rshell)
==36925==    by 0x40281F: main (in /home/csmajs/hchu007/rshell/bin/rshell)
==36925==  Address 0x4c39243 is 0 bytes after a block of size 3 alloc'd
==36925==    at 0x4A07192: operator new[](unsigned long) (vg_replace_malloc.c:363)
==36925==    by 0x401AB2: execute(std::vector<std::string, std::allocator<std::string> >) (in /home/csmajs/hchu007/rshell/bin/rshell)
==36925==    by 0x402160: pipes1(std::vector<std::string, std::allocator<std::string> >) (in /home/csmajs/hchu007/rshell/bin/rshell)
==36925==    by 0x40281F: main (in /home/csmajs/hchu007/rshell/bin/rshell)
==36925== 
==36925== Invalid read of size 2
==36925==    at 0x4A08DAC: memcpy (mc_replace_strmem.c:882)
==36925==    by 0x30508AD5C6: execvpe (in /lib64/libc-2.12.so)
==36925==    by 0x401B24: execute(std::vector<std::string, std::allocator<std::string> >) (in /home/csmajs/hchu007/rshell/bin/rshell)
==36925==    by 0x402160: pipes1(std::vector<std::string, std::allocator<std::string> >) (in /home/csmajs/hchu007/rshell/bin/rshell)
==36925==    by 0x40281F: main (in /home/csmajs/hchu007/rshell/bin/rshell)
==36925==  Address 0x4c39242 is 2 bytes inside a block of size 3 alloc'd
==36925==    at 0x4A07192: operator new[](unsigned long) (vg_replace_malloc.c:363)
==36925==    by 0x401AB2: execute(std::vector<std::string, std::allocator<std::string> >) (in /home/csmajs/hchu007/rshell/bin/rshell)
==36925==    by 0x402160: pipes1(std::vector<std::string, std::allocator<std::string> >) (in /home/csmajs/hchu007/rshell/bin/rshell)
==36925==    by 0x40281F: main (in /home/csmajs/hchu007/rshell/bin/rshell)
==36925== 
==36925== Syscall param execve(argv[i]) points to unaddressable byte(s)
==36925==    at 0x30508ACDA7: execve (in /lib64/libc-2.12.so)
==36925==    by 0x30508AD630: execvpe (in /lib64/libc-2.12.so)
==36925==    by 0x401B24: execute(std::vector<std::string, std::allocator<std::string> >) (in /home/csmajs/hchu007/rshell/bin/rshell)
==36925==    by 0x402160: pipes1(std::vector<std::string, std::allocator<std::string> >) (in /home/csmajs/hchu007/rshell/bin/rshell)
==36925==    by 0x40281F: main (in /home/csmajs/hchu007/rshell/bin/rshell)
==36925==  Address 0x4c39243 is 0 bytes after a block of size 3 alloc'd
==36925==    at 0x4A07192: operator new[](unsigned long) (vg_replace_malloc.c:363)
==36925==    by 0x401AB2: execute(std::vector<std::string, std::allocator<std::string> >) (in /home/csmajs/hchu007/rshell/bin/rshell)
==36925==    by 0x402160: pipes1(std::vector<std::string, std::allocator<std::string> >) (in /home/csmajs/hchu007/rshell/bin/rshell)
==36925==    by 0x40281F: main (in /home/csmajs/hchu007/rshell/bin/rshell)
==36925== 
==36926== Invalid write of size 1
==36926==    at 0x4A080CF: __GI_strcpy (mc_replace_strmem.c:443)
==36926==    by 0x401AF2: execute(std::vector<std::string, std::allocator<std::string> >) (in /home/csmajs/hchu007/rshell/bin/rshell)
==36926==    by 0x402160: pipes1(std::vector<std::string, std::allocator<std::string> >) (in /home/csmajs/hchu007/rshell/bin/rshell)
==36926==    by 0x402233: pipes1(std::vector<std::string, std::allocator<std::string> >) (in /home/csmajs/hchu007/rshell/bin/rshell)
==36926==    by 0x40281F: main (in /home/csmajs/hchu007/rshell/bin/rshell)
==36926==  Address 0x4c39632 is 0 bytes after a block of size 2 alloc'd
==36926==    at 0x4A07192: operator new[](unsigned long) (vg_replace_malloc.c:363)
==36926==    by 0x401AB2: execute(std::vector<std::string, std::allocator<std::string> >) (in /home/csmajs/hchu007/rshell/bin/rshell)
==36926==    by 0x402160: pipes1(std::vector<std::string, std::allocator<std::string> >) (in /home/csmajs/hchu007/rshell/bin/rshell)
==36926==    by 0x402233: pipes1(std::vector<std::string, std::allocator<std::string> >) (in /home/csmajs/hchu007/rshell/bin/rshell)
==36926==    by 0x40281F: main (in /home/csmajs/hchu007/rshell/bin/rshell)
==36926== 
==36926== Invalid read of size 1
==36926==    at 0x4A07B84: __GI_strchr (mc_replace_strmem.c:223)
==36926==    by 0x30508AD423: execvpe (in /lib64/libc-2.12.so)
==36926==    by 0x401B24: execute(std::vector<std::string, std::allocator<std::string> >) (in /home/csmajs/hchu007/rshell/bin/rshell)
==36926==    by 0x402160: pipes1(std::vector<std::string, std::allocator<std::string> >) (in /home/csmajs/hchu007/rshell/bin/rshell)
==36926==    by 0x402233: pipes1(std::vector<std::string, std::allocator<std::string> >) (in /home/csmajs/hchu007/rshell/bin/rshell)
==36926==    by 0x40281F: main (in /home/csmajs/hchu007/rshell/bin/rshell)
==36926==  Address 0x4c39632 is 0 bytes after a block of size 2 alloc'd
==36926==    at 0x4A07192: operator new[](unsigned long) (vg_replace_malloc.c:363)
==36926==    by 0x401AB2: execute(std::vector<std::string, std::allocator<std::string> >) (in /home/csmajs/hchu007/rshell/bin/rshell)
==36926==    by 0x402160: pipes1(std::vector<std::string, std::allocator<std::string> >) (in /home/csmajs/hchu007/rshell/bin/rshell)
==36926==    by 0x402233: pipes1(std::vector<std::string, std::allocator<std::string> >) (in /home/csmajs/hchu007/rshell/bin/rshell)
==36926==    by 0x40281F: main (in /home/csmajs/hchu007/rshell/bin/rshell)
==36926== 
==36926== Invalid read of size 1
==36926==    at 0x4A07FC4: __GI_strlen (mc_replace_strmem.c:404)
==36926==    by 0x30508AD56C: execvpe (in /lib64/libc-2.12.so)
==36926==    by 0x401B24: execute(std::vector<std::string, std::allocator<std::string> >) (in /home/csmajs/hchu007/rshell/bin/rshell)
==36926==    by 0x402160: pipes1(std::vector<std::string, std::allocator<std::string> >) (in /home/csmajs/hchu007/rshell/bin/rshell)
==36926==    by 0x402233: pipes1(std::vector<std::string, std::allocator<std::string> >) (in /home/csmajs/hchu007/rshell/bin/rshell)
==36926==    by 0x40281F: main (in /home/csmajs/hchu007/rshell/bin/rshell)
==36926==  Address 0x4c39632 is 0 bytes after a block of size 2 alloc'd
==36926==    at 0x4A07192: operator new[](unsigned long) (vg_replace_malloc.c:363)
==36926==    by 0x401AB2: execute(std::vector<std::string, std::allocator<std::string> >) (in /home/csmajs/hchu007/rshell/bin/rshell)
==36926==    by 0x402160: pipes1(std::vector<std::string, std::allocator<std::string> >) (in /home/csmajs/hchu007/rshell/bin/rshell)
==36926==    by 0x402233: pipes1(std::vector<std::string, std::allocator<std::string> >) (in /home/csmajs/hchu007/rshell/bin/rshell)
==36926==    by 0x40281F: main (in /home/csmajs/hchu007/rshell/bin/rshell)
==36926== 
==36926== Invalid read of size 1
==36926==    at 0x4A08DEC: memcpy (mc_replace_strmem.c:882)
==36926==    by 0x30508AD5C6: execvpe (in /lib64/libc-2.12.so)
==36926==    by 0x401B24: execute(std::vector<std::string, std::allocator<std::string> >) (in /home/csmajs/hchu007/rshell/bin/rshell)
==36926==    by 0x402160: pipes1(std::vector<std::string, std::allocator<std::string> >) (in /home/csmajs/hchu007/rshell/bin/rshell)
==36926==    by 0x402233: pipes1(std::vector<std::string, std::allocator<std::string> >) (in /home/csmajs/hchu007/rshell/bin/rshell)
==36926==    by 0x40281F: main (in /home/csmajs/hchu007/rshell/bin/rshell)
==36926==  Address 0x4c39632 is 0 bytes after a block of size 2 alloc'd
==36926==    at 0x4A07192: operator new[](unsigned long) (vg_replace_malloc.c:363)
==36926==    by 0x401AB2: execute(std::vector<std::string, std::allocator<std::string> >) (in /home/csmajs/hchu007/rshell/bin/rshell)
==36926==    by 0x402160: pipes1(std::vector<std::string, std::allocator<std::string> >) (in /home/csmajs/hchu007/rshell/bin/rshell)
==36926==    by 0x402233: pipes1(std::vector<std::string, std::allocator<std::string> >) (in /home/csmajs/hchu007/rshell/bin/rshell)
==36926==    by 0x40281F: main (in /home/csmajs/hchu007/rshell/bin/rshell)
==36926== 
==36926== Syscall param execve(argv[i]) points to unaddressable byte(s)
==36926==    at 0x30508ACDA7: execve (in /lib64/libc-2.12.so)
==36926==    by 0x30508AD630: execvpe (in /lib64/libc-2.12.so)
==36926==    by 0x401B24: execute(std::vector<std::string, std::allocator<std::string> >) (in /home/csmajs/hchu007/rshell/bin/rshell)
==36926==    by 0x402160: pipes1(std::vector<std::string, std::allocator<std::string> >) (in /home/csmajs/hchu007/rshell/bin/rshell)
==36926==    by 0x402233: pipes1(std::vector<std::string, std::allocator<std::string> >) (in /home/csmajs/hchu007/rshell/bin/rshell)
==36926==    by 0x40281F: main (in /home/csmajs/hchu007/rshell/bin/rshell)
==36926==  Address 0x4c39632 is 0 bytes after a block of size 2 alloc'd
==36926==    at 0x4A07192: operator new[](unsigned long) (vg_replace_malloc.c:363)
==36926==    by 0x401AB2: execute(std::vector<std::string, std::allocator<std::string> >) (in /home/csmajs/hchu007/rshell/bin/rshell)
==36926==    by 0x402160: pipes1(std::vector<std::string, std::allocator<std::string> >) (in /home/csmajs/hchu007/rshell/bin/rshell)
==36926==    by 0x402233: pipes1(std::vector<std::string, std::allocator<std::string> >) (in /home/csmajs/hchu007/rshell/bin/rshell)
==36926==    by 0x40281F: main (in /home/csmajs/hchu007/rshell/bin/rshell)
==36926== 
==36927== Invalid write of size 1
==36927==    at 0x4A080CF: __GI_strcpy (mc_replace_strmem.c:443)
==36927==    by 0x401AF2: execute(std::vector<std::string, std::allocator<std::string> >) (in /home/csmajs/hchu007/rshell/bin/rshell)
==36927==    by 0x402160: pipes1(std::vector<std::string, std::allocator<std::string> >) (in /home/csmajs/hchu007/rshell/bin/rshell)
==36927==    by 0x402233: pipes1(std::vector<std::string, std::allocator<std::string> >) (in /home/csmajs/hchu007/rshell/bin/rshell)
==36927==    by 0x402233: pipes1(std::vector<std::string, std::allocator<std::string> >) (in /home/csmajs/hchu007/rshell/bin/rshell)
==36927==    by 0x40281F: main (in /home/csmajs/hchu007/rshell/bin/rshell)
==36927==  Address 0x4c398d3 is 0 bytes after a block of size 3 alloc'd
==36927==    at 0x4A07192: operator new[](unsigned long) (vg_replace_malloc.c:363)
==36927==    by 0x401AB2: execute(std::vector<std::string, std::allocator<std::string> >) (in /home/csmajs/hchu007/rshell/bin/rshell)
==36927==    by 0x402160: pipes1(std::vector<std::string, std::allocator<std::string> >) (in /home/csmajs/hchu007/rshell/bin/rshell)
==36927==    by 0x402233: pipes1(std::vector<std::string, std::allocator<std::string> >) (in /home/csmajs/hchu007/rshell/bin/rshell)
==36927==    by 0x402233: pipes1(std::vector<std::string, std::allocator<std::string> >) (in /home/csmajs/hchu007/rshell/bin/rshell)
==36927==    by 0x40281F: main (in /home/csmajs/hchu007/rshell/bin/rshell)
==36927== 
==36927== Invalid read of size 1
==36927==    at 0x4A07B84: __GI_strchr (mc_replace_strmem.c:223)
==36927==    by 0x30508AD423: execvpe (in /lib64/libc-2.12.so)
==36927==    by 0x401B24: execute(std::vector<std::string, std::allocator<std::string> >) (in /home/csmajs/hchu007/rshell/bin/rshell)
==36927==    by 0x402160: pipes1(std::vector<std::string, std::allocator<std::string> >) (in /home/csmajs/hchu007/rshell/bin/rshell)
==36927==    by 0x402233: pipes1(std::vector<std::string, std::allocator<std::string> >) (in /home/csmajs/hchu007/rshell/bin/rshell)
==36927==    by 0x402233: pipes1(std::vector<std::string, std::allocator<std::string> >) (in /home/csmajs/hchu007/rshell/bin/rshell)
==36927==    by 0x40281F: main (in /home/csmajs/hchu007/rshell/bin/rshell)
==36927==  Address 0x4c398d3 is 0 bytes after a block of size 3 alloc'd
==36927==    at 0x4A07192: operator new[](unsigned long) (vg_replace_malloc.c:363)
==36927==    by 0x401AB2: execute(std::vector<std::string, std::allocator<std::string> >) (in /home/csmajs/hchu007/rshell/bin/rshell)
==36927==    by 0x402160: pipes1(std::vector<std::string, std::allocator<std::string> >) (in /home/csmajs/hchu007/rshell/bin/rshell)
==36927==    by 0x402233: pipes1(std::vector<std::string, std::allocator<std::string> >) (in /home/csmajs/hchu007/rshell/bin/rshell)
==36927==    by 0x402233: pipes1(std::vector<std::string, std::allocator<std::string> >) (in /home/csmajs/hchu007/rshell/bin/rshell)
==36927==    by 0x40281F: main (in /home/csmajs/hchu007/rshell/bin/rshell)
==36927== 
==36927== Invalid read of size 1
==36927==    at 0x4A07FC4: __GI_strlen (mc_replace_strmem.c:404)
==36927==    by 0x30508AD56C: execvpe (in /lib64/libc-2.12.so)
==36927==    by 0x401B24: execute(std::vector<std::string, std::allocator<std::string> >) (in /home/csmajs/hchu007/rshell/bin/rshell)
==36927==    by 0x402160: pipes1(std::vector<std::string, std::allocator<std::string> >) (in /home/csmajs/hchu007/rshell/bin/rshell)
==36927==    by 0x402233: pipes1(std::vector<std::string, std::allocator<std::string> >) (in /home/csmajs/hchu007/rshell/bin/rshell)
==36927==    by 0x402233: pipes1(std::vector<std::string, std::allocator<std::string> >) (in /home/csmajs/hchu007/rshell/bin/rshell)
==36927==    by 0x40281F: main (in /home/csmajs/hchu007/rshell/bin/rshell)
==36927==  Address 0x4c398d3 is 0 bytes after a block of size 3 alloc'd
==36927==    at 0x4A07192: operator new[](unsigned long) (vg_replace_malloc.c:363)
==36927==    by 0x401AB2: execute(std::vector<std::string, std::allocator<std::string> >) (in /home/csmajs/hchu007/rshell/bin/rshell)
==36927==    by 0x402160: pipes1(std::vector<std::string, std::allocator<std::string> >) (in /home/csmajs/hchu007/rshell/bin/rshell)
==36927==    by 0x402233: pipes1(std::vector<std::string, std::allocator<std::string> >) (in /home/csmajs/hchu007/rshell/bin/rshell)
==36927==    by 0x402233: pipes1(std::vector<std::string, std::allocator<std::string> >) (in /home/csmajs/hchu007/rshell/bin/rshell)
==36927==    by 0x40281F: main (in /home/csmajs/hchu007/rshell/bin/rshell)
==36927== 
==36927== Invalid read of size 2
==36927==    at 0x4A08DAC: memcpy (mc_replace_strmem.c:882)
==36927==    by 0x30508AD5C6: execvpe (in /lib64/libc-2.12.so)
==36927==    by 0x401B24: execute(std::vector<std::string, std::allocator<std::string> >) (in /home/csmajs/hchu007/rshell/bin/rshell)
==36927==    by 0x402160: pipes1(std::vector<std::string, std::allocator<std::string> >) (in /home/csmajs/hchu007/rshell/bin/rshell)
==36927==    by 0x402233: pipes1(std::vector<std::string, std::allocator<std::string> >) (in /home/csmajs/hchu007/rshell/bin/rshell)
==36927==    by 0x402233: pipes1(std::vector<std::string, std::allocator<std::string> >) (in /home/csmajs/hchu007/rshell/bin/rshell)
==36927==    by 0x40281F: main (in /home/csmajs/hchu007/rshell/bin/rshell)
==36927==  Address 0x4c398d2 is 2 bytes inside a block of size 3 alloc'd
==36927==    at 0x4A07192: operator new[](unsigned long) (vg_replace_malloc.c:363)
==36927==    by 0x401AB2: execute(std::vector<std::string, std::allocator<std::string> >) (in /home/csmajs/hchu007/rshell/bin/rshell)
==36927==    by 0x402160: pipes1(std::vector<std::string, std::allocator<std::string> >) (in /home/csmajs/hchu007/rshell/bin/rshell)
==36927==    by 0x402233: pipes1(std::vector<std::string, std::allocator<std::string> >) (in /home/csmajs/hchu007/rshell/bin/rshell)
==36927==    by 0x402233: pipes1(std::vector<std::string, std::allocator<std::string> >) (in /home/csmajs/hchu007/rshell/bin/rshell)
==36927==    by 0x40281F: main (in /home/csmajs/hchu007/rshell/bin/rshell)
==36927== 
==36927== Syscall param execve(argv[i]) points to unaddressable byte(s)
==36927==    at 0x30508ACDA7: execve (in /lib64/libc-2.12.so)
==36927==    by 0x30508AD630: execvpe (in /lib64/libc-2.12.so)
==36927==    by 0x401B24: execute(std::vector<std::string, std::allocator<std::string> >) (in /home/csmajs/hchu007/rshell/bin/rshell)
==36927==    by 0x402160: pipes1(std::vector<std::string, std::allocator<std::string> >) (in /home/csmajs/hchu007/rshell/bin/rshell)
==36927==    by 0x402233: pipes1(std::vector<std::string, std::allocator<std::string> >) (in /home/csmajs/hchu007/rshell/bin/rshell)
==36927==    by 0x402233: pipes1(std::vector<std::string, std::allocator<std::string> >) (in /home/csmajs/hchu007/rshell/bin/rshell)
==36927==    by 0x40281F: main (in /home/csmajs/hchu007/rshell/bin/rshell)
==36927==  Address 0x4c398d3 is 0 bytes after a block of size 3 alloc'd
==36927==    at 0x4A07192: operator new[](unsigned long) (vg_replace_malloc.c:363)
==36927==    by 0x401AB2: execute(std::vector<std::string, std::allocator<std::string> >) (in /home/csmajs/hchu007/rshell/bin/rshell)
==36927==    by 0x402160: pipes1(std::vector<std::string, std::allocator<std::string> >) (in /home/csmajs/hchu007/rshell/bin/rshell)
==36927==    by 0x402233: pipes1(std::vector<std::string, std::allocator<std::string> >) (in /home/csmajs/hchu007/rshell/bin/rshell)
==36927==    by 0x402233: pipes1(std::vector<std::string, std::allocator<std::string> >) (in /home/csmajs/hchu007/rshell/bin/rshell)
==36927==    by 0x40281F: main (in /home/csmajs/hchu007/rshell/bin/rshell)
==36927== 
==36924== Invalid write of size 1
==36924==    at 0x4A080CF: __GI_strcpy (mc_replace_strmem.c:443)
==36924==    by 0x401AF2: execute(std::vector<std::string, std::allocator<std::string> >) (in /home/csmajs/hchu007/rshell/bin/rshell)
==36924==    by 0x4020A0: pipes1(std::vector<std::string, std::allocator<std::string> >) (in /home/csmajs/hchu007/rshell/bin/rshell)
==36924==    by 0x402233: pipes1(std::vector<std::string, std::allocator<std::string> >) (in /home/csmajs/hchu007/rshell/bin/rshell)
==36924==    by 0x402233: pipes1(std::vector<std::string, std::allocator<std::string> >) (in /home/csmajs/hchu007/rshell/bin/rshell)
==36924==    by 0x402233: pipes1(std::vector<std::string, std::allocator<std::string> >) (in /home/csmajs/hchu007/rshell/bin/rshell)
==36924==    by 0x40281F: main (in /home/csmajs/hchu007/rshell/bin/rshell)
==36924==  Address 0x4c39b02 is 0 bytes after a block of size 2 alloc'd
==36924==    at 0x4A07192: operator new[](unsigned long) (vg_replace_malloc.c:363)
==36924==    by 0x401AB2: execute(std::vector<std::string, std::allocator<std::string> >) (in /home/csmajs/hchu007/rshell/bin/rshell)
==36924==    by 0x4020A0: pipes1(std::vector<std::string, std::allocator<std::string> >) (in /home/csmajs/hchu007/rshell/bin/rshell)
==36924==    by 0x402233: pipes1(std::vector<std::string, std::allocator<std::string> >) (in /home/csmajs/hchu007/rshell/bin/rshell)
==36924==    by 0x402233: pipes1(std::vector<std::string, std::allocator<std::string> >) (in /home/csmajs/hchu007/rshell/bin/rshell)
==36924==    by 0x402233: pipes1(std::vector<std::string, std::allocator<std::string> >) (in /home/csmajs/hchu007/rshell/bin/rshell)
==36924==    by 0x40281F: main (in /home/csmajs/hchu007/rshell/bin/rshell)
==36924== 
==36924== Invalid read of size 1
==36924==    at 0x4A08538: __GI_strcmp (mc_replace_strmem.c:730)
==36924==    by 0x401879: checkIO(char**) (in /home/csmajs/hchu007/rshell/bin/rshell)
==36924==    by 0x401B0E: execute(std::vector<std::string, std::allocator<std::string> >) (in /home/csmajs/hchu007/rshell/bin/rshell)
==36924==    by 0x4020A0: pipes1(std::vector<std::string, std::allocator<std::string> >) (in /home/csmajs/hchu007/rshell/bin/rshell)
==36924==    by 0x402233: pipes1(std::vector<std::string, std::allocator<std::string> >) (in /home/csmajs/hchu007/rshell/bin/rshell)
==36924==    by 0x402233: pipes1(std::vector<std::string, std::allocator<std::string> >) (in /home/csmajs/hchu007/rshell/bin/rshell)
==36924==    by 0x402233: pipes1(std::vector<std::string, std::allocator<std::string> >) (in /home/csmajs/hchu007/rshell/bin/rshell)
==36924==    by 0x40281F: main (in /home/csmajs/hchu007/rshell/bin/rshell)
==36924==  Address 0x4c39bf1 is 0 bytes after a block of size 1 alloc'd
==36924==    at 0x4A07192: operator new[](unsigned long) (vg_replace_malloc.c:363)
==36924==    by 0x401AB2: execute(std::vector<std::string, std::allocator<std::string> >) (in /home/csmajs/hchu007/rshell/bin/rshell)
==36924==    by 0x4020A0: pipes1(std::vector<std::string, std::allocator<std::string> >) (in /home/csmajs/hchu007/rshell/bin/rshell)
==36924==    by 0x402233: pipes1(std::vector<std::string, std::allocator<std::string> >) (in /home/csmajs/hchu007/rshell/bin/rshell)
==36924==    by 0x402233: pipes1(std::vector<std::string, std::allocator<std::string> >) (in /home/csmajs/hchu007/rshell/bin/rshell)
==36924==    by 0x402233: pipes1(std::vector<std::string, std::allocator<std::string> >) (in /home/csmajs/hchu007/rshell/bin/rshell)
==36924==    by 0x40281F: main (in /home/csmajs/hchu007/rshell/bin/rshell)
==36924== 
==36924== Syscall param open(filename) points to unaddressable byte(s)
==36924==    at 0x30508DB3B0: __open_nocancel (in /lib64/libc-2.12.so)
==36924==    by 0x4019AE: checkIO(char**) (in /home/csmajs/hchu007/rshell/bin/rshell)
==36924==    by 0x401B0E: execute(std::vector<std::string, std::allocator<std::string> >) (in /home/csmajs/hchu007/rshell/bin/rshell)
==36924==    by 0x4020A0: pipes1(std::vector<std::string, std::allocator<std::string> >) (in /home/csmajs/hchu007/rshell/bin/rshell)
==36924==    by 0x402233: pipes1(std::vector<std::string, std::allocator<std::string> >) (in /home/csmajs/hchu007/rshell/bin/rshell)
==36924==    by 0x402233: pipes1(std::vector<std::string, std::allocator<std::string> >) (in /home/csmajs/hchu007/rshell/bin/rshell)
==36924==    by 0x402233: pipes1(std::vector<std::string, std::allocator<std::string> >) (in /home/csmajs/hchu007/rshell/bin/rshell)
==36924==    by 0x40281F: main (in /home/csmajs/hchu007/rshell/bin/rshell)
==36924==  Address 0x4c39c47 is 0 bytes after a block of size 7 alloc'd
==36924==    at 0x4A07192: operator new[](unsigned long) (vg_replace_malloc.c:363)
==36924==    by 0x401AB2: execute(std::vector<std::string, std::allocator<std::string> >) (in /home/csmajs/hchu007/rshell/bin/rshell)
==36924==    by 0x4020A0: pipes1(std::vector<std::string, std::allocator<std::string> >) (in /home/csmajs/hchu007/rshell/bin/rshell)
==36924==    by 0x402233: pipes1(std::vector<std::string, std::allocator<std::string> >) (in /home/csmajs/hchu007/rshell/bin/rshell)
==36924==    by 0x402233: pipes1(std::vector<std::string, std::allocator<std::string> >) (in /home/csmajs/hchu007/rshell/bin/rshell)
==36924==    by 0x402233: pipes1(std::vector<std::string, std::allocator<std::string> >) (in /home/csmajs/hchu007/rshell/bin/rshell)
==36924==    by 0x40281F: main (in /home/csmajs/hchu007/rshell/bin/rshell)
==36924== 
==36924== Invalid read of size 1
==36924==    at 0x4A07B84: __GI_strchr (mc_replace_strmem.c:223)
==36924==    by 0x30508AD423: execvpe (in /lib64/libc-2.12.so)
==36924==    by 0x401B24: execute(std::vector<std::string, std::allocator<std::string> >) (in /home/csmajs/hchu007/rshell/bin/rshell)
==36924==    by 0x4020A0: pipes1(std::vector<std::string, std::allocator<std::string> >) (in /home/csmajs/hchu007/rshell/bin/rshell)
==36924==    by 0x402233: pipes1(std::vector<std::string, std::allocator<std::string> >) (in /home/csmajs/hchu007/rshell/bin/rshell)
==36924==    by 0x402233: pipes1(std::vector<std::string, std::allocator<std::string> >) (in /home/csmajs/hchu007/rshell/bin/rshell)
==36924==    by 0x402233: pipes1(std::vector<std::string, std::allocator<std::string> >) (in /home/csmajs/hchu007/rshell/bin/rshell)
==36924==    by 0x40281F: main (in /home/csmajs/hchu007/rshell/bin/rshell)
==36924==  Address 0x4c39b02 is 0 bytes after a block of size 2 alloc'd
==36924==    at 0x4A07192: operator new[](unsigned long) (vg_replace_malloc.c:363)
==36924==    by 0x401AB2: execute(std::vector<std::string, std::allocator<std::string> >) (in /home/csmajs/hchu007/rshell/bin/rshell)
==36924==    by 0x4020A0: pipes1(std::vector<std::string, std::allocator<std::string> >) (in /home/csmajs/hchu007/rshell/bin/rshell)
==36924==    by 0x402233: pipes1(std::vector<std::string, std::allocator<std::string> >) (in /home/csmajs/hchu007/rshell/bin/rshell)
==36924==    by 0x402233: pipes1(std::vector<std::string, std::allocator<std::string> >) (in /home/csmajs/hchu007/rshell/bin/rshell)
==36924==    by 0x402233: pipes1(std::vector<std::string, std::allocator<std::string> >) (in /home/csmajs/hchu007/rshell/bin/rshell)
==36924==    by 0x40281F: main (in /home/csmajs/hchu007/rshell/bin/rshell)
==36924== 
==36924== Invalid read of size 1
==36924==    at 0x4A07FC4: __GI_strlen (mc_replace_strmem.c:404)
==36924==    by 0x30508AD56C: execvpe (in /lib64/libc-2.12.so)
==36924==    by 0x401B24: execute(std::vector<std::string, std::allocator<std::string> >) (in /home/csmajs/hchu007/rshell/bin/rshell)
==36924==    by 0x4020A0: pipes1(std::vector<std::string, std::allocator<std::string> >) (in /home/csmajs/hchu007/rshell/bin/rshell)
==36924==    by 0x402233: pipes1(std::vector<std::string, std::allocator<std::string> >) (in /home/csmajs/hchu007/rshell/bin/rshell)
==36924==    by 0x402233: pipes1(std::vector<std::string, std::allocator<std::string> >) (in /home/csmajs/hchu007/rshell/bin/rshell)
==36924==    by 0x402233: pipes1(std::vector<std::string, std::allocator<std::string> >) (in /home/csmajs/hchu007/rshell/bin/rshell)
==36924==    by 0x40281F: main (in /home/csmajs/hchu007/rshell/bin/rshell)
==36924==  Address 0x4c39b02 is 0 bytes after a block of size 2 alloc'd
==36924==    at 0x4A07192: operator new[](unsigned long) (vg_replace_malloc.c:363)
==36924==    by 0x401AB2: execute(std::vector<std::string, std::allocator<std::string> >) (in /home/csmajs/hchu007/rshell/bin/rshell)
==36924==    by 0x4020A0: pipes1(std::vector<std::string, std::allocator<std::string> >) (in /home/csmajs/hchu007/rshell/bin/rshell)
==36924==    by 0x402233: pipes1(std::vector<std::string, std::allocator<std::string> >) (in /home/csmajs/hchu007/rshell/bin/rshell)
==36924==    by 0x402233: pipes1(std::vector<std::string, std::allocator<std::string> >) (in /home/csmajs/hchu007/rshell/bin/rshell)
==36924==    by 0x402233: pipes1(std::vector<std::string, std::allocator<std::string> >) (in /home/csmajs/hchu007/rshell/bin/rshell)
==36924==    by 0x40281F: main (in /home/csmajs/hchu007/rshell/bin/rshell)
==36924== 
==36924== Invalid read of size 1
==36924==    at 0x4A08DEC: memcpy (mc_replace_strmem.c:882)
==36924==    by 0x30508AD5C6: execvpe (in /lib64/libc-2.12.so)
==36924==    by 0x401B24: execute(std::vector<std::string, std::allocator<std::string> >) (in /home/csmajs/hchu007/rshell/bin/rshell)
==36924==    by 0x4020A0: pipes1(std::vector<std::string, std::allocator<std::string> >) (in /home/csmajs/hchu007/rshell/bin/rshell)
==36924==    by 0x402233: pipes1(std::vector<std::string, std::allocator<std::string> >) (in /home/csmajs/hchu007/rshell/bin/rshell)
==36924==    by 0x402233: pipes1(std::vector<std::string, std::allocator<std::string> >) (in /home/csmajs/hchu007/rshell/bin/rshell)
==36924==    by 0x402233: pipes1(std::vector<std::string, std::allocator<std::string> >) (in /home/csmajs/hchu007/rshell/bin/rshell)
==36924==    by 0x40281F: main (in /home/csmajs/hchu007/rshell/bin/rshell)
==36924==  Address 0x4c39b02 is 0 bytes after a block of size 2 alloc'd
==36924==    at 0x4A07192: operator new[](unsigned long) (vg_replace_malloc.c:363)
==36924==    by 0x401AB2: execute(std::vector<std::string, std::allocator<std::string> >) (in /home/csmajs/hchu007/rshell/bin/rshell)
==36924==    by 0x4020A0: pipes1(std::vector<std::string, std::allocator<std::string> >) (in /home/csmajs/hchu007/rshell/bin/rshell)
==36924==    by 0x402233: pipes1(std::vector<std::string, std::allocator<std::string> >) (in /home/csmajs/hchu007/rshell/bin/rshell)
==36924==    by 0x402233: pipes1(std::vector<std::string, std::allocator<std::string> >) (in /home/csmajs/hchu007/rshell/bin/rshell)
==36924==    by 0x402233: pipes1(std::vector<std::string, std::allocator<std::string> >) (in /home/csmajs/hchu007/rshell/bin/rshell)
==36924==    by 0x40281F: main (in /home/csmajs/hchu007/rshell/bin/rshell)
==36924== 
==36924== Syscall param execve(argv[i]) points to unaddressable byte(s)
==36924==    at 0x30508ACDA7: execve (in /lib64/libc-2.12.so)
==36924==    by 0x30508AD630: execvpe (in /lib64/libc-2.12.so)
==36924==    by 0x401B24: execute(std::vector<std::string, std::allocator<std::string> >) (in /home/csmajs/hchu007/rshell/bin/rshell)
==36924==    by 0x4020A0: pipes1(std::vector<std::string, std::allocator<std::string> >) (in /home/csmajs/hchu007/rshell/bin/rshell)
==36924==    by 0x402233: pipes1(std::vector<std::string, std::allocator<std::string> >) (in /home/csmajs/hchu007/rshell/bin/rshell)
==36924==    by 0x402233: pipes1(std::vector<std::string, std::allocator<std::string> >) (in /home/csmajs/hchu007/rshell/bin/rshell)
==36924==    by 0x402233: pipes1(std::vector<std::string, std::allocator<std::string> >) (in /home/csmajs/hchu007/rshell/bin/rshell)
==36924==    by 0x40281F: main (in /home/csmajs/hchu007/rshell/bin/rshell)
==36924==  Address 0x4c39b02 is 0 bytes after a block of size 2 alloc'd
==36924==    at 0x4A07192: operator new[](unsigned long) (vg_replace_malloc.c:363)
==36924==    by 0x401AB2: execute(std::vector<std::string, std::allocator<std::string> >) (in /home/csmajs/hchu007/rshell/bin/rshell)
==36924==    by 0x4020A0: pipes1(std::vector<std::string, std::allocator<std::string> >) (in /home/csmajs/hchu007/rshell/bin/rshell)
==36924==    by 0x402233: pipes1(std::vector<std::string, std::allocator<std::string> >) (in /home/csmajs/hchu007/rshell/bin/rshell)
==36924==    by 0x402233: pipes1(std::vector<std::string, std::allocator<std::string> >) (in /home/csmajs/hchu007/rshell/bin/rshell)
==36924==    by 0x402233: pipes1(std::vector<std::string, std::allocator<std::string> >) (in /home/csmajs/hchu007/rshell/bin/rshell)
==36924==    by 0x40281F: main (in /home/csmajs/hchu007/rshell/bin/rshell)
==36924== 
hchu007@hammer.cs.ucr.edu$ exitex   t
==36887== 
==36887== HEAP SUMMARY:
==36887==     in use at exit: 0 bytes in 0 blocks
==36887==   total heap usage: 158 allocs, 158 frees, 65,976 bytes allocated
==36887== 
==36887== All heap blocks were freed -- no leaks are possible
==36887== 
==36887== For counts of detected and suppressed errors, rerun with: -v
==36887== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 6 from 6)
~/rshell
hchu007@hammer $ #END TEST
~/rshell
hchu007@hammer $ exit
exit

Script done on Tue 18 Nov 2014 08:53:12 PM PST
